// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Serif } from "next/font/google";
import Header from "./global/Header";
import HeaderWrapper from "./global/HeaderWrapper";
import FooterWrapper from "./global/FooterWrapper";

// Restore GeistSans font
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",  // Ensure this file exists in the 'public/fonts/' folder
  variable: "--font-geist-sans",
  weight: "100 900",
});

// Restore GeistMono font
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",  // Ensure this file exists in the 'public/fonts/' folder
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Google font Noto Serif
const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${notoSerif.variable}
          antialiased
          bg-beige
          text-[#000000]
          font-serif
        `}
      >
        <HeaderWrapper />
        {children}
        <FooterWrapper />
      </body>
    </html>
  );
}
