import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Serif } from "next/font/google";
import Header from "./global/Header";
import HeaderWrapper from "./global/HeaderWrapper";
import FooterWrapper from "./global/FooterWrapper";
import { LanguageProvider } from "./LanguageContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerif.variable}
          antialiased
          bg-beige
          text-[#000000]
          font-serif
        `}
      >
        <LanguageProvider>
        <HeaderWrapper />
        {children}
        <FooterWrapper />
        </LanguageProvider>
      </body>
    </html>
  );
}
